// ============================================================
// CROP PLAN DATA — 658 Lefthand Branch Road
// Extracted from trial-crop-plan-v2.html
// Used to pre-populate Assets and inform task generation
// ============================================================

export const CROP_PLAN_META = {
  property: '658 Lefthand Branch Road',
  location: 'Lockyer Valley QLD',
  trialStart: 'Apr 2026',
  firstIncome: 'Jun 2026',
  setupCostTotal: '~$1,450',
  y3Revenue: '$28,000–68,000',
  startOrder: ['Nasturtium', 'Finger Lime', 'Vanilla', 'Wasabi'],
};

// Status: active | trial | viable | monitor | hard | illegal
export const CROPS = [
  // ── ACTIVE (already in operating plan) ──────────────────
  { id: 1,  icon: '🫒', name: 'Table olives',            cat: 'Tree fruit',        status: 'active',  revenue: '$15–30/kg cured',            setup: '$0 (existing grove)', timeToIncome: 'May 2027 partial',  qty: 300,  qtyUnit: 'trees',    zone: 'Olive grove',               weatherSensitive: true,  weatherCondition: 'dry',           tags: ['harvest', 'NASAA', 'QRIDA'] },
  { id: 2,  icon: '🥚', name: 'Free-range eggs',         cat: 'Poultry',           status: 'active',  revenue: '$7.50–10/doz farmgate',      setup: '$3,200',              timeToIncome: 'May 2026 (2 weeks)', qty: 75,   qtyUnit: 'hens',     zone: 'Paddock — poultry',         weatherSensitive: false, weatherCondition: 'any',           tags: ['daily', 'income'] },
  { id: 3,  icon: '🍯', name: 'Honey — European bees',   cat: 'Bees',              status: 'active',  revenue: '$18–25/kg · first Feb 2027', setup: '$600–800',            timeToIncome: 'Feb 2027',           qty: 2,    qtyUnit: 'hives',    zone: 'Olive grove — hive sites',  weatherSensitive: true,  weatherCondition: 'dry',           tags: ['bees', 'harvest'] },
  { id: 4,  icon: '🌿', name: 'Industrial hemp',         cat: 'Field crop',        status: 'active',  revenue: '$3,500–5,000/season',        setup: '$400',                timeToIncome: 'Jan 2027',           qty: 0.6,  qtyUnit: 'ha',       zone: 'Central field',             weatherSensitive: true,  weatherCondition: 'dry',           tags: ['DAF licence', 'contract'] },
  { id: 5,  icon: '🐟', name: 'Jade Perch — aquaponics', cat: 'Aquaculture',       status: 'active',  revenue: '$15–25/kg whole',            setup: '$9,500',              timeToIncome: 'Late 2027',          qty: 350,  qtyUnit: 'fingerlings', zone: 'Aquaponics system',        weatherSensitive: false, weatherCondition: 'any',           tags: ['DAF licence', 'aquaculture'] },

  // ── TRIAL CROPS (detailed plans) ────────────────────────
  { id: 6,  icon: '🌸', name: 'Nasturtium',              cat: 'Edible flower',     status: 'trial',   revenue: '$150–600/kg · $6–8/punnet',  setup: '$15',                 timeToIncome: '6–8 weeks',          qty: 50,   qtyUnit: 'plants',   zone: 'Morning shade — macadamia row', weatherSensitive: false, weatherCondition: 'any',       tags: ['fast income', 'restaurant'] },
  { id: 7,  icon: '🟢', name: 'Finger lime',             cat: 'Native citrus',     status: 'trial',   revenue: '$60–120/kg fresh',           setup: '$450–600',            timeToIncome: '2–3 years',          qty: 10,   qtyUnit: 'trees',    zone: 'Eastern macadamia shade band', weatherSensitive: false, weatherCondition: 'any',        tags: ['grafted', 'propagation'] },
  { id: 8,  icon: '🌿', name: 'Vanilla',                 cat: 'Orchid vine',       status: 'trial',   revenue: '$400–600/kg cured',          setup: '$200–350',            timeToIncome: '3 years to flower',  qty: 20,   qtyUnit: 'cuttings', zone: 'Macadamia shade zone',      weatherSensitive: false, weatherCondition: 'any',           tags: ['hand pollination', 'curing'] },
  { id: 9,  icon: '🌊', name: 'Wasabi',                  cat: 'Rhizome',           status: 'trial',   revenue: '$250–400/kg stem',           setup: '$600–800',            timeToIncome: '18–24 months',       qty: 40,   qtyUnit: 'plants',   zone: 'Tent Hill Creek riparian',   weatherSensitive: true,  weatherCondition: 'no_extreme_heat', tags: ['restaurant direct', 'creek', 'biosecurity'] },

  // ── VIABLE — READY TO START ──────────────────────────────
  { id: 10, icon: '🫛', name: 'Ginger',                  cat: 'Rhizome',           status: 'viable',  revenue: '$35–45/kg organic',          setup: '$400–800',            timeToIncome: '8–10 months',        qty: null, qtyUnit: 'kg seed',  zone: 'Full sun beds',             weatherSensitive: true,  weatherCondition: 'dry',           tags: ['biosecurity cert', 'value-add'] },
  { id: 11, icon: '🟡', name: 'Turmeric',                cat: 'Rhizome',           status: 'viable',  revenue: '$18–25/kg · $60–80/kg dried', setup: '$200–400',           timeToIncome: '8–10 months',        qty: null, qtyUnit: 'kg seed',  zone: 'Macadamia shade band',      weatherSensitive: true,  weatherCondition: 'dry',           tags: ['value-add', 'powder'] },
  { id: 12, icon: '🟤', name: 'Galangal',                cat: 'Rhizome',           status: 'viable',  revenue: '$15–22/kg fresh',            setup: '$150–300',            timeToIncome: '8–10 months',        qty: null, qtyUnit: null,       zone: 'Full sun / part shade',     weatherSensitive: false, weatherCondition: 'any',           tags: ['Asian market'] },
  { id: 13, icon: '🍋', name: 'Makrut lime leaves',      cat: 'Native citrus',     status: 'viable',  revenue: '$40–100/kg eq',              setup: '$300–500',            timeToIncome: '1–2 years',          qty: 12,   qtyUnit: 'trees',    zone: 'Eastern macadamia shade band', weatherSensitive: false, weatherCondition: 'any',        tags: ['restaurant', 'thorns'] },
  { id: 14, icon: '🌱', name: 'Lemongrass',              cat: 'Perennial herb',    status: 'viable',  revenue: '$25–35/kg wholesale',        setup: '$100–200',            timeToIncome: '6–8 months',         qty: null, qtyUnit: 'clumps',   zone: 'Full sun / macadamia row',  weatherSensitive: false, weatherCondition: 'any',           tags: ['perennial', 'low input'] },
  { id: 15, icon: '🌿', name: 'Asian herbs (mixed)',     cat: 'Annual herb',       status: 'viable',  revenue: '$20–40/kg restaurant',       setup: '$50–100',             timeToIncome: '6–8 weeks',          qty: null, qtyUnit: null,       zone: 'Macadamia shade zone',      weatherSensitive: false, weatherCondition: 'any',           tags: ['Vietnamese mint', 'perilla', 'Thai basil'] },
  { id: 16, icon: '🌻', name: 'Sunflowers',              cat: 'Edible flower',     status: 'viable',  revenue: '$3–8/stem · $8–15/kg seed',  setup: '$30–50',              timeToIncome: '8–12 weeks',         qty: null, qtyUnit: null,       zone: 'Full sun',                  weatherSensitive: true,  weatherCondition: 'dry',           tags: ['cut flower', 'seed'] },
  { id: 17, icon: '🌼', name: 'Borage / violas / calendula', cat: 'Edible flower', status: 'viable', revenue: '$150–400/kg · $6–10/punnet', setup: '$30',                 timeToIncome: '6–10 weeks',         qty: null, qtyUnit: null,       zone: 'Alongside nasturtium beds', weatherSensitive: false, weatherCondition: 'any',           tags: ['bee forage', 'restaurant garnish'] },
  { id: 18, icon: '🫚', name: 'Olive leaf tea / extract', cat: 'By-product',       status: 'viable',  revenue: '$20–40/kg dried',            setup: '$0',                  timeToIncome: 'Immediate',          qty: null, qtyUnit: null,       zone: 'Olive grove (pruning waste)', weatherSensitive: false, weatherCondition: 'any',        tags: ['value-add', 'pruning waste'] },
  { id: 19, icon: '🌰', name: 'Macadamia nuts',          cat: 'Tree nut',          status: 'viable',  revenue: '$8–15/kg shell · $25–40/kg kernel', setup: '$0',           timeToIncome: 'Ongoing',            qty: 1,    qtyUnit: 'tree',     zone: 'Existing tree',             weatherSensitive: false, weatherCondition: 'any',           tags: ['propagation'] },
  { id: 20, icon: '☕', name: 'Coffee (arabica)',         cat: 'Tree crop',         status: 'viable',  revenue: '$60–120/kg roasted',         setup: '$400–800',            timeToIncome: '3–4 years',          qty: 50,   qtyUnit: 'seedlings', zone: 'Macadamia shade band',      weatherSensitive: false, weatherCondition: 'any',           tags: ['long term', 'value-add'] },
  { id: 21, icon: '🍫', name: 'Cacao',                   cat: 'Tree crop',         status: 'viable',  revenue: '$60–300/kg processed',       setup: '$500–1,000',          timeToIncome: '3–5 years',          qty: null, qtyUnit: 'trees',    zone: 'Creek riparian / macadamia', weatherSensitive: false, weatherCondition: 'any',           tags: ['bean-to-bar', 'long term'] },
  { id: 22, icon: '🌶', name: 'Specialty chillies',      cat: 'Annual/perennial',  status: 'viable',  revenue: '$80–200/kg dried',           setup: '$100–200',            timeToIncome: '3–4 months',         qty: null, qtyUnit: null,       zone: 'Full sun / part shade',     weatherSensitive: false, weatherCondition: 'any',           tags: ['superhot', 'value-add'] },
  { id: 23, icon: '🧄', name: 'Garlic',                  cat: 'Annual bulb',       status: 'viable',  revenue: '$15–30/kg organic',          setup: '$200–400',            timeToIncome: '6–8 months',         qty: null, qtyUnit: 'kg seed',  zone: 'Central field (Apr–Nov)',   weatherSensitive: true,  weatherCondition: 'dry',           tags: ['Lockyer Valley specialty', 'black garlic'] },
  { id: 24, icon: '🧅', name: 'Shallots / spring onions', cat: 'Annual bulb',      status: 'viable',  revenue: '$4–8/kg',                    setup: '$100–200',            timeToIncome: '8–12 weeks',         qty: null, qtyUnit: null,       zone: 'Field rotation',            weatherSensitive: false, weatherCondition: 'any',           tags: ['rotation crop', 'Asian market'] },
  { id: 25, icon: '🍠', name: 'Sweet potato (specialty)', cat: 'Vine/root',        status: 'viable',  revenue: '$6–12/kg specialty',         setup: '$100–200',            timeToIncome: '3–4 months',         qty: null, qtyUnit: null,       zone: 'Field rotation',            weatherSensitive: false, weatherCondition: 'any',           tags: ['Murasaki', 'Japanese variety', 'Asian market'] },
  { id: 26, icon: '🍌', name: 'Bananas (Lady Finger)',    cat: 'Tree crop',         status: 'viable',  revenue: '$8–12/kg farmgate',          setup: '$300–600',            timeToIncome: '12–15 months',       qty: null, qtyUnit: 'suckers',  zone: 'Sheltered full sun',        weatherSensitive: true,  weatherCondition: 'dry',           tags: ['wind shelter required'] },
  { id: 27, icon: '🍍', name: 'Pineapples (Sugarloaf)',   cat: 'Bromeliad',         status: 'viable',  revenue: '$8–15 each farmgate',        setup: '$200–400',            timeToIncome: '18–24 months',       qty: null, qtyUnit: 'crowns',   zone: 'Full sun low slope',        weatherSensitive: false, weatherCondition: 'any',           tags: ['self-perpetuating', 'premium variety'] },
  { id: 28, icon: '🥭', name: 'Mango (Honey Gold / R2E2)', cat: 'Tree fruit',      status: 'viable',  revenue: '$6–12 each farmgate',        setup: '$500–1,000',          timeToIncome: '2–3 years',          qty: 10,   qtyUnit: 'trees',    zone: 'Northern field boundary',   weatherSensitive: false, weatherCondition: 'any',           tags: ['premium variety'] },
  { id: 29, icon: '🥑', name: 'Avocado',                  cat: 'Tree fruit',        status: 'viable',  revenue: '$3–8/kg farmgate',           setup: '$500–1,000',          timeToIncome: '2–4 years',          qty: 8,    qtyUnit: 'trees',    zone: 'Eastern section, well-drained', weatherSensitive: false, weatherCondition: 'any',        tags: ['bore irrigation required'] },
  { id: 30, icon: '🍓', name: 'Strawberries (raised bed)', cat: 'Berry',           status: 'viable',  revenue: '$8–15/kg · PYO premium',     setup: '$500–1,000',          timeToIncome: '6–8 months',         qty: null, qtyUnit: null,       zone: 'Raised beds (Apr–Sep)',     weatherSensitive: true,  weatherCondition: 'dry',           tags: ['Lockyer Valley specialty', 'agritourism'] },
  { id: 31, icon: '🍇', name: 'Passionfruit',             cat: 'Vine',              status: 'viable',  revenue: '$8–15/kg',                   setup: '$200–400',            timeToIncome: '18 months',          qty: null, qtyUnit: 'vines',    zone: 'Fence trellis',             weatherSensitive: false, weatherCondition: 'any',           tags: ['Panama Red', 'grafted'] },
  { id: 32, icon: '🍈', name: 'Davidson plum',            cat: 'Native fruit',      status: 'viable',  revenue: '$15–30/kg · $40–80/kg processed', setup: '$300–500',       timeToIncome: '3–5 years',          qty: 10,   qtyUnit: 'trees',    zone: 'Macadamia shade band',      weatherSensitive: false, weatherCondition: 'any',           tags: ['native food', 'jam/sauce'] },
  { id: 33, icon: '🌺', name: 'Lemon myrtle',             cat: 'Native herb',       status: 'viable',  revenue: '$25–60/kg dried leaf',       setup: '$200–400',            timeToIncome: '2–3 years',          qty: 12,   qtyUnit: 'trees',    zone: 'Understorey shade zone',    weatherSensitive: false, weatherCondition: 'any',           tags: ['native food', 'essential oil', 'cosmetics'] },
  { id: 34, icon: '🌿', name: 'Native pepperberry',       cat: 'Native spice',      status: 'viable',  revenue: '$60–120/kg dried berry',     setup: '$200–400',            timeToIncome: '2–3 years',          qty: 10,   qtyUnit: 'plants',   zone: 'Shade zone — trial first',  weatherSensitive: false, weatherCondition: 'any',           tags: ['artisan spice', 'trial 10 first'] },
  { id: 53, icon: '🍐', name: 'Feijoa',                   cat: 'Fruit',             status: 'viable',  revenue: '$8–15/kg very undersupplied', setup: '$400–800',           timeToIncome: '2–3 years',          qty: 8,    qtyUnit: 'trees',    zone: 'Full sun / part shade',     weatherSensitive: false, weatherCondition: 'any',           tags: ['undersupplied', 'self-fertile'] },
  { id: 54, icon: '🌶', name: 'Pepperoncini / sweet peppers', cat: 'Annual veg',   status: 'viable',  revenue: '$12–20/kg jarred',           setup: '$100–200',            timeToIncome: '3–4 months',         qty: null, qtyUnit: null,       zone: 'Full sun',                  weatherSensitive: false, weatherCondition: 'any',           tags: ['value-add', 'jarred product', 'shed'] },
  { id: 52, icon: '🍑', name: 'Low-chill peaches',        cat: 'Stone fruit',       status: 'monitor', revenue: '$3–8/kg farmgate',           setup: '$800–1,500',          timeToIncome: '2–3 years',          qty: null, qtyUnit: 'trees',    zone: 'Full sun',                  weatherSensitive: false, weatherCondition: 'any',           tags: ['Flordaprince', 'low-chill variety'] },

  // ── WATCH LIST ───────────────────────────────────────────
  { id: 35, icon: '🌺', name: 'Saffron',                  cat: 'Bulb',              status: 'monitor', revenue: '$8,000–80,000/kg',           setup: '$500–2,000',          timeToIncome: '6 months if flowers', qty: null, qtyUnit: null,      zone: 'Greenhouse only',           weatherSensitive: false, weatherCondition: 'any',           tags: ['climate mismatch — too warm'], note: 'Climate barrier. Needs greenhouse.' },
  { id: 36, icon: '🍄', name: 'Gourmet mushrooms',        cat: 'Fungi',             status: 'monitor', revenue: '$20–100/kg',                 setup: '$500–1,500',          timeToIncome: '6–8 weeks',           qty: null, qtyUnit: null,      zone: 'Shed grow room',            weatherSensitive: false, weatherCondition: 'any',           tags: ['revisit at shed build'], note: 'Natural fit once processing shed is built.' },
  { id: 37, icon: '🎍', name: 'Bamboo (edible shoots)',   cat: 'Grass',             status: 'monitor', revenue: '$8–40/kg',                   setup: '$300–600',            timeToIncome: '2–3 years',           qty: null, qtyUnit: null,      zone: 'Creek riparian bank',       weatherSensitive: false, weatherCondition: 'any',           tags: ['clumping species only', 'bank stabilisation'], note: 'Revisit Year 2. Bank stabilisation bonus.' },
  { id: 38, icon: '🌿', name: 'Moringa',                  cat: 'Tree crop',         status: 'monitor', revenue: '$80–150/kg powder',          setup: '$100–200',            timeToIncome: '6 months',            qty: 25,   qtyUnit: 'trees',   zone: 'Central field full sun',    weatherSensitive: false, weatherCondition: 'any',           tags: ['fast growing', 'low cost trial'], note: 'Low cost trial worth starting Year 1.' },
  { id: 39, icon: '🌹', name: 'Native cut flowers',       cat: 'Cut flower',        status: 'monitor', revenue: '$1–5/stem',                  setup: '$500–1,500',          timeToIncome: '6–12 months',         qty: null, qtyUnit: null,      zone: 'Acid soil zones only',      weatherSensitive: false, weatherCondition: 'any',           tags: ['Protea', 'Banksia', 'soil test first'], note: 'Revisit after soil testing.' },
  { id: 40, icon: '🌺', name: 'Agave',                    cat: 'Succulent',         status: 'monitor', revenue: '$3–25/kg',                   setup: '$300–600',            timeToIncome: '5–10 years',          qty: null, qtyUnit: 'pups',    zone: 'Rocky / poor soil margins', weatherSensitive: false, weatherCondition: 'any',           tags: ['fibre', 'syrup', 'long term'] },
  { id: 41, icon: '🌾', name: 'Teff / ancient grains',    cat: 'Grain',             status: 'monitor', revenue: '$4–12/kg specialty',         setup: '$200–400',            timeToIncome: '3–4 months',          qty: null, qtyUnit: null,      zone: 'Inner field rotation',      weatherSensitive: false, weatherCondition: 'any',           tags: ['gluten-free market', 'Year 2'] },
  { id: 42, icon: '🌿', name: 'Medical cannabis',         cat: 'Controlled crop',   status: 'monitor', revenue: '$3,000–8,000/kg flower',     setup: '$50,000+ licence',    timeToIncome: '12–24 months licence', qty: null, qtyUnit: null,     zone: 'Secure facility required', weatherSensitive: false, weatherCondition: 'any',           tags: ['ODC licence', 'revisit Year 5'], note: 'Revisit at Year 5 when compliance infrastructure in place.' },
  { id: 55, icon: '🌿', name: 'Aloe vera',                cat: 'Succulent',         status: 'monitor', revenue: '$20–60/L extract',           setup: '$200–400',            timeToIncome: '2–3 years',           qty: null, qtyUnit: 'pups',    zone: 'Full sun dry areas',        weatherSensitive: false, weatherCondition: 'any',           tags: ['cosmetics', 'revisit at shed'] },

  // ── TOO HARD ─────────────────────────────────────────────
  { id: 43, icon: '🌴', name: 'Durian',                   cat: 'Tropical fruit',    status: 'hard',    revenue: '$30–80/kg',                  setup: '$1,000–2,000',        timeToIncome: '4–6 years',           qty: null, qtyUnit: null,      zone: 'N/A — climate barrier',    weatherSensitive: false, weatherCondition: 'any',           tags: ['too cold in winter'], note: 'Climate barrier. Revisit 2040s.' },
  { id: 50, icon: '🫐', name: 'Blueberries',              cat: 'Berry',             status: 'hard',    revenue: '$8–20/kg',                   setup: '$3,000–6,000',        timeToIncome: '2–3 years',           qty: null, qtyUnit: null,      zone: 'Raised acid beds',         weatherSensitive: false, weatherCondition: 'any',           tags: ['soil acidification intensive'], note: 'Revisit after soil pH testing.' },
  { id: 51, icon: '🍒', name: 'Cherries',                 cat: 'Stone fruit',       status: 'hard',    revenue: '$25–60/kg',                  setup: '$2,000–4,000',        timeToIncome: '3–5 years',           qty: null, qtyUnit: null,      zone: 'N/A — insufficient chill', weatherSensitive: false, weatherCondition: 'any',           tags: ['insufficient chill hours'], note: 'Only ~200–400 chill hrs vs 800–1200 needed.' },

  // ── ILLEGAL ──────────────────────────────────────────────
  { id: 44, icon: '🌿', name: 'Coca',                     cat: 'Controlled plant',  status: 'illegal', revenue: 'N/A', setup: 'N/A', timeToIncome: 'N/A', qty: null, qtyUnit: null, zone: 'N/A', weatherSensitive: false, weatherCondition: 'any', tags: ['Schedule 9'], note: 'Illegal. Not viable.' },
  { id: 45, icon: '🌺', name: 'Opium poppy',              cat: 'Controlled plant',  status: 'illegal', revenue: 'N/A', setup: 'N/A', timeToIncome: 'N/A', qty: null, qtyUnit: null, zone: 'N/A', weatherSensitive: false, weatherCondition: 'any', tags: ['TAS only'], note: 'Legal only in Tasmania under PACB.' },
  { id: 46, icon: '🌵', name: 'Peyote / mescaline cacti', cat: 'Controlled plant',  status: 'illegal', revenue: 'N/A', setup: 'N/A', timeToIncome: 'N/A', qty: null, qtyUnit: null, zone: 'N/A', weatherSensitive: false, weatherCondition: 'any', tags: ['Schedule 9'], note: 'Illegal.' },
  { id: 47, icon: '🌿', name: 'Khat',                     cat: 'Controlled plant',  status: 'illegal', revenue: 'N/A', setup: 'N/A', timeToIncome: 'N/A', qty: null, qtyUnit: null, zone: 'N/A', weatherSensitive: false, weatherCondition: 'any', tags: ['Schedule 9'], note: 'Illegal.' },
  { id: 48, icon: '🍄', name: 'Psilocybin mushrooms',     cat: 'Controlled fungi',  status: 'illegal', revenue: 'N/A', setup: 'N/A', timeToIncome: 'N/A', qty: null, qtyUnit: null, zone: 'N/A', weatherSensitive: false, weatherCondition: 'any', tags: ['Schedule 9 QLD'], note: 'Illegal for commercial cultivation.' },
  { id: 49, icon: '🌱', name: 'Kratom',                   cat: 'Controlled plant',  status: 'illegal', revenue: 'N/A', setup: 'N/A', timeToIncome: 'N/A', qty: null, qtyUnit: null, zone: 'N/A', weatherSensitive: false, weatherCondition: 'any', tags: ['Schedule 9 QLD'], note: 'Illegal in QLD.' },
];

// Status labels & colours for UI
export const STATUS_CONFIG = {
  active:  { label: 'In plan',    color: '#4e7453', bg: '#c4dbc6' },
  trial:   { label: 'Trial crop', color: '#2a6980', bg: '#c8e8f0' },
  viable:  { label: 'Viable',     color: '#7a9e7e', bg: '#e8f4e8' },
  monitor: { label: 'Watch list', color: '#c8a96e', bg: '#f5edd8' },
  hard:    { label: 'Too hard',   color: '#9a7d6a', bg: '#ede3dc' },
  illegal: { label: 'Illegal',    color: '#b85c38', bg: '#f5ddd4' },
};

// Get crops that are active/trial (used for asset pre-population)
export const getActionableCrops = () =>
  CROPS.filter(c => c.status === 'active' || c.status === 'trial');

// Get crops that generate calendar-relevant tasks
export const getCropsWithTasks = () =>
  CROPS.filter(c => ['active', 'trial', 'viable'].includes(c.status));
